### ISSUE TITLE
Small issues

### ISSUE THREAD

**Issue by jmartins-ledger** [LedgerHQ/app-plugin-1inch#12]
1. Remove unnecessary [debug](https://github.com/LedgerHQ/app-plugin-1inch/blob/f04df741a782f7664b98f78fdb69999a40582c31/src/one_inch_plugin.h#L6) include.
2. Add a static assert in [one_inch_plugin.h](https://github.com/LedgerHQ/app-plugin-1inch/blob/f04df741a782f7664b98f78fdb69999a40582c31/src/one_inch_plugin.h#L108) just like in [boilerplate](https://github.com/LedgerHQ/app-plugin-boilerplate/blob/313b4a1c2fc86f16fa3ce2852382b3f1708edb67/src/boilerplate_plugin.h#L59-L61).

**Comment by adrienlacombe-ledger** [comment]
@GuilaneDen is this something small enough for you to take? ty ty

**Comment by GuilaneDen** [comment]
Hello @adrienlacombe-ledger, you can find the updated version here: https://github.com/blooo-io/app-plugin-1inch

**Comment by adrienlacombe-ledger** [comment]
thank you so much @GuilaneDen !

**Comment by adrienlacombe-ledger** [comment]
@jmartins-ledger can we please close? thank you vm

**Comment by jmartins-ledger** [comment]
@adrienlacombe-ledger yes!

**Comment by adrienlacombe-ledger** [comment]
I don't have the rights to do it :sweat_smile:

**Comment by apaillier-ledger** [comment]
Fixed by #14

**Comment by adrienlacombe-ledger** [comment]
:beau:
